config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: {  
  confirmations: 'users/confirmations',
  passwords: 'users/passwords',
  registrations: 'users/registrations',
  sessions: 'users/sessions',
  # unlocks: 'users/unlocks',
  }, skip: [:sessions, :passwords]

  # devise_for :users

  as :user do 
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    delete 'logout' => 'users/sessions#destroy', as: :destroy_user_session
    get 'sign_up' => 'users/registrations#new'
    get 'users/password/reset' => 'users/passwords#new', as: :new_user_password
    post 'users/password/reset' => 'users/passwords#create', as: :user_password
    get 'users/psasword/reset/edit' => 'users/passwords#edit', as: :edit_user_password
    put 'users/password/reset' => 'users/passwords#update'
    patch 'users/password/reset' => 'users/passwords#update'
    get 'users/password/reset/done' => 'users/passwords#done', as: :done_user_password
    # post 'validation' => 'users/sessions#login_validataion', as: :user_login_validataion
  end

  as :profile do
    get 'profiles' => 'profile#show', as: :profile
    post 'profiles' => 'profile#create', as: :create_profile
    put 'profiles' => 'profile#update'
    patch 'profiles' => 'profile#update'
  end

  as :project do
    get 'projects' => 'project#new', as: :new_project
    get 'projects/:project_id' => 'project#show', as: :show_project
    post 'projects/:project_id' => 'project#show'
    post 'projects/:project_id/relation' => 'project#relation', as: :image_relation_project
    post 'projects/:project_id/videos/section' => 'project#section', as: :video_section_project
    # get 'project/:project_id/relation' => 'project#relation'
    post 'projects' => 'project#create', as: :create_project
    post 'projects/:project_id/preview' => 'project#preview', as: :preview_project
    post 'projects/validate/:project_id' => 'project#project_validate', as: :validate_project_id
    get 'projects/:project_id/preview' => 'project#preview'
    put 'projects' => 'project#update', as: :project
    patch 'projects' => 'project#update'
  end

  as :image do
    post 'projects/:project_id/images' => 'image#create', as: :create_project_image
    delete 'projects/:project_id/images/:image_id' => 'image#destroy', as: :destroy_project_image
    post 'projects/:project_id/images/destroy_all' => 'image#destroy_all', as: :destroy_all_project_image
    post 'projects/images/create' => 'image#create', as: :create_image
    put 'projects/:project_id/images' => 'image#update', as: :image
    patch 'projects/:project_id/images' => 'image#update'
  end

  as :clickables do
    post 'projects/:project_id/images/:image_id/clickables' => 'clickable#create', as: :project_image_clickables
    post 'projects/:project_id/images/:image_id/clickables/destroy_all' => 'clickable#destroy_all', as: :destroy_all_project_image_clickables
  end

  as :video do
    post 'api/videos/' => 'video#api_create', as: :api_create_project_video
  end

  as :video_clickables do
    post 'projects/:project_id/videos/:video_id/clickables' => 'video_clickable#create', as: :project_video_clickables
    post 'projects/:project_id/videos/:video_id/clickables/destroy_all' => 'video_clickable#destroy_all', as: :destroy_all_project_video_clickables
  end

  as :token do
    post 'tokens/validation' => 'application#validation', as: :token_validation
  end

  get 'landing' => 'page#landing', as: :page_landing
  # get 'home' => 'page#home', as: :page_home
  get 'privacy' => 'page#privacy', as: :page_privacy
  get 'term' => 'page#term', as: :page_term
  get 'home' => 'page#search'
  post 'home' => 'page#search', as: :project_search

  get 'test' => 'page#test'

  root 'page#landing'
end

app/views/shared/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <div class="text">
    (주)쇼미더앱스 | 서울특별시 강남구 역삼로 215 남국빌딩 2층 쇼미더앱스 | 
    <%= link_to '이용약관', page_term_path %> | 
    <%= link_to '개인정보처리방침', page_privacy_path %>
    </br>contact@showmetheapps.co
  </div>
</footer>

app/views/shared/_form.html.erb
<!-- <= simple_form_for  %> -->

app/views/shared/_header.html.erb
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%= link_to 'HOME', project_search_path, onclick: 'closeNav()' %>

  <% if user_signed_in? %>
    <%= link_to "UPLOAD", new_project_path, method: :get, onclick: 'closeNav()' %>
    <%= link_to "PROFILE", profile_path, method: :get, onclick: 'closeNav()' %>
    <%= link_to "LOGOUT", destroy_user_session_path, method: :delete, onclick: 'closeNav()' %>
  <% else %>
    <%= link_to "LOGIN", '', class: "userModal", id: 'login', onclick: 'closeNav()' %>
  <% end %>
</div>

<!-- <header> -->
<div class="header">
  <div class="navbar navbar-fixed-top navbar-default">
    <div class="container">
    <%= link_to image_tag('/assets/header/logo.svg', class: 'logo vertical-center', size: '106x38'), project_search_path %>

    <% if controller.action_name == 'search' %>
      <%= render 'shared/header_form' %>
    <% end %>

    <%= image_tag '/assets/header/menu_icon.svg', class: 'menu vertical-center', size: '27x27', onClick: 'openNav()'%>
    </div>
  </div>
  </div>
<!-- </header> -->

app/views/shared/_header_form.html.erb
<div class="searchbox">
  <%= search_form_for @search, url: project_search_path, method: :post do |f| %>
    <%= f.text_field :name_cont, class: 'search-field' %>
    <%= image_submit_tag asset_path('header/header_search_icon.png'), class: 'search-submit'%>
  <% end %>
</div>

<script type="text/javascript">
  if ("<%= @browser %>" == "phone") {
    $('.searchbox').hide();
  }

  $(window).resize(function(e) {
    if( $(this).width() <= 430 ) {
      $('.searchbox').hide();
    } else {
      $('.searchbox').show();
    }
  });

</script>

app/views/shared/_usermodal.html.erb
<div class="modal fade" id="userModal" role="dialog">
    <div class="login-modal-content">
      <div class="bg"></div>
      <div class="modal-header">
        <%= image_tag '/assets/landing/usermodal/close.svg', class: 'close', data: {dismiss: 'modal'} %>
      </div>
      <div class="modal-body">
        <%= image_tag '/assets/landing/logo.svg', class: 'logo' %>

        <div class="regist-login">
          <div class="title">
            <div class="regist">
              <%= image_tag '/assets/landing/usermodal/regist.svg', id: 'regist-image' %>
              회원가입
            </div>
            <div class="login">
            <%= image_tag '/assets/landing/usermodal/login.svg', id: 'login-image' %>
              로그인
            </div>
          </div>
          <div class="body">
            <div class="modal-regist">
              <%= simple_form_for(resource, as: resource_name, remote: true, url: registration_path(resource_name), id: 'regist-form') do |f| %>

                <div class="email-form">
                  <%= f.input :email, required: true, autofocus: true, label: false, placeholder: "이메일 입력", input_html: { class: "regist-email", autocomplete: 'on' } %>
                  <%= image_tag '/assets/landing/usermodal/email.svg', class: 'regist-email-img' %>
                </div>
                <div class="email-form-error">이메일을 정확히 입력해 주세요.</div>
                <div class="pw-form">
                  <%= f.input :password, required: true, label: false, placeholder: "비밀번호 입력", input_html: { class: "regist-pw" }%>
                  <%= image_tag '/assets/landing/usermodal/password.svg', class: 'regist-pw-img' %>
                </div>
                <div class="pw-form-error">비밀번호는 4글자 이상, 숫자를 포함하여 만들어주세요.</div>

                <div class="email-check-form">
                  <%= f.check_box :email_check, checked: true %>
                  <label><span></span>이메일 수신 동의</label>
                  <%= link_to '이용약관', page_term_path, class: 'link-term' %> | 
                  <%= link_to '개인정보처리방침', page_privacy_path, class: 'link-privacy' %>
                </div>
                <div class="email-check-text">
                  - 동의를 하시면 댜양한 쇼미더앱스의 안내를 받아보실 수 있습니다.
                </div>
                <!-- <= f.input :password_confirmation, required: true %> -->
                <%= f.button :submit, "확인", class: 'submit-regist-btn submit' %>
                <% end %>
            </div>

            

            <div class="modal-login">
              <%= simple_form_for(resource, as: resource_name, format: :json, remote: true, url: session_path(resource_name), id: 'login-form') do |f| %>
              <div class="email-form">
                <%= f.input :email, required: true, autofocus: true, label: false, placeholder: "이메일 입력", input_html: { class: "login-email", autocomplete: 'on'} %>
                <%= image_tag '/assets/landing/usermodal/email.svg', class: 'login-email-img' %>
              </div>
              <div class="email-form-error">이메일을 정확히 입력해 주세요.</div>
              <div class="pw-form">
                <%= f.input :password, required: true, label: false, placeholder: "비밀번호 입력", input_html: { class: "login-pw"} %>
                <%= image_tag '/assets/landing/usermodal/password.svg', class: 'login-pw-img' %>
              </div>
              <div class="pw-form-error"></div>
              <div class="autologin-check-form">
                <%= f.check_box :remember_me, checked: true, label: false, as: :boolean if devise_mapping.rememberable? %>
                <label><span></span>자동 로그인</label>
                <%= link_to '비밀번호 변경', new_user_password_path, class: 'link-privacy' %>
              </div>
              <%= f.button :submit, "확인", class: 'submit-login-btn' %>
              <% end %>
            </div>
            
            
          </div>
          
          
          
        </div>

      </div>
      <div class="modal-footer">
      </div>
    </div>
    
</div>