config/routes.rb
Rails.application.routes.draw do
  devise_for :user, controllers: {  
  confirmations: 'users/confirmations',
  passwords: 'users/passwords',
  registrations: 'users/registrations',
  sessions: 'users/sessions',
  # unlocks: 'users/unlocks',
  }, skip: [:sessions, :passwords]

  # devise_for :users

  as :user do 
    get 'login' => 'users/sessions#new', as: :new_user_session
    post 'login' => 'users/sessions#create', as: :user_session
    delete 'logout' => 'users/sessions#destroy', as: :destroy_user_session
    get 'sign_up' => 'users/registrations#new'
    get 'users/password/reset' => 'users/passwords#new', as: :new_user_password
    post 'users/password/reset' => 'users/passwords#create', as: :user_password
    get 'users/psasword/reset/edit' => 'users/passwords#edit', as: :edit_user_password
    put 'users/password/reset' => 'users/passwords#update'
    patch 'users/password/reset' => 'users/passwords#update'
    get 'users/password/reset/done' => 'users/passwords#done', as: :done_user_password
    # post 'validation' => 'users/sessions#login_validataion', as: :user_login_validataion
  end

  as :profile do
    get 'profiles' => 'profile#show', as: :profile
    post 'profiles' => 'profile#create', as: :create_profile
    put 'profiles' => 'profile#update'
    patch 'profiles' => 'profile#update'
  end

  as :project do
    get 'projects' => 'project#new', as: :new_project
    get 'projects/:project_id' => 'project#show', as: :show_project
    post 'projects/:project_id' => 'project#show'
    post 'projects/:project_id/relation' => 'project#relation', as: :image_relation_project
    post 'projects/:project_id/videos/section' => 'project#section', as: :video_section_project
    # get 'project/:project_id/relation' => 'project#relation'
    post 'projects' => 'project#create', as: :create_project
    post 'projects/:project_id/preview' => 'project#preview', as: :preview_project
    post 'projects/validate/:project_id' => 'project#project_validate', as: :validate_project_id
    get 'projects/:project_id/preview' => 'project#preview'
    put 'projects' => 'project#update', as: :project
    patch 'projects' => 'project#update'
  end

  as :image do
    post 'projects/:project_id/images' => 'image#create', as: :create_project_image
    delete 'projects/:project_id/images/:image_id' => 'image#destroy', as: :destroy_project_image
    post 'projects/:project_id/images/destroy_all' => 'image#destroy_all', as: :destroy_all_project_image
    post 'projects/images/create' => 'image#create', as: :create_image
    put 'projects/:project_id/images' => 'image#update', as: :image
    patch 'projects/:project_id/images' => 'image#update'
  end

  as :clickables do
    post 'projects/:project_id/images/:image_id/clickables' => 'clickable#create', as: :project_image_clickables
    post 'projects/:project_id/images/:image_id/clickables/destroy_all' => 'clickable#destroy_all', as: :destroy_all_project_image_clickables
  end

  as :video do
    post 'api/videos/' => 'video#api_create', as: :api_create_project_video
  end

  as :video_clickables do
    post 'projects/:project_id/videos/:video_id/clickables' => 'video_clickable#create', as: :project_video_clickables
    post 'projects/:project_id/videos/:video_id/clickables/destroy_all' => 'video_clickable#destroy_all', as: :destroy_all_project_video_clickables
  end

  as :token do
    post 'tokens/validation' => 'application#validation', as: :token_validation
  end

  get 'landing' => 'page#landing', as: :page_landing
  # get 'home' => 'page#home', as: :page_home
  get 'privacy' => 'page#privacy', as: :page_privacy
  get 'term' => 'page#term', as: :page_term
  get 'home' => 'page#search'
  post 'home' => 'page#search', as: :project_search

  get 'test' => 'page#test'

  root 'page#landing'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :users
  has_many :images, dependent: :destroy
  has_one :video, dependent: :destroy

  def type project_id
    return true if Image.find_by_project_id project_id
    return false if Video.find_by_project_id project_id

  end

end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  before_action :authenticate_user!, only: [:update, :show, :create, :relation]
  before_action :set_project, only: [:show, :update, :relation, :preview, :section]

  def new
    @project = current_user.projects.new
    @project.name = ""
    @project.desc = ""
    @images = @project.images

  end

  def create
    @project = current_user.projects.build(project_params)
    if @project.save
      render status: 200, json: @project, nothing: true
    else
      render nothing: true, status: 304
    end
  end

  def destroy

  end

  def destroy_all

  end

  def update
    @project.name = params[:project][:name]
    @project.desc = params[:project][:desc]

    if @project.save
      render nothing: true, status: :ok
    else
      render nothing: true, status: 304
    end
  end

  def show
    @images = @project.images.all
    @videos = @project.video
    gon.param = params[:project_id]
  end

  def relation
    @images = @project.images.all
    unless (params[:image_id]).nil?
      @image = Image.find(params[:image_id])
    else
      @image = @images.first
    end
    @image_id = @image.id
    render "project/relation"
  end

  def section
    @video = @project.video
    @video_id = @video.id
    @video.video_clickables.each(&:destroy)
    # render "project/section"
  end

  def preview
    @project_manager = gon.project_manager = project_manager?(@project.id) if @project.id

    unless @project.type @project.id
      @video = @project.video 
      @clickables = @video.video_clickables.order("time ASC")
    end

    if @project.type @project.id
      @images = @project.images.all

      unless (params[:image_id]).nil?
        @image = Image.find(params[:image_id])
      else
        @image = @images.first
      end
    end

  end

  def preview_image
    
  end

  def preview_video
    
  end

  def project_validate
    if Project.find_by_name(params[:project_name]).nil?
      render nothing: true, status: 200, json: {"message": "validate"}
    else
      render nothing: true, status: 226, json: {"message": "invalidate"}
    end
  end

  private
  def project_params
    params.require(:project).permit(:name, :desc)
  end

  def set_project
    id = params[:project_id]
    return @project = Project.find(id) if id
    return @project = current_user.projects.find_by_name(params[:project_name]) if params[:project_name]
  end

  def project_manager? project_id
    # preview mode true   -> guest
    # preview mode false  -> manager
    return false if !user_signed_in?

    current_project = Project.find(project_id)
    current_user.projects.each do |projects|
      return true if current_project == projects
    end

    return false
  end

end

app/views/project/_form.html.erb
<div class="project-info">
  <%= simple_form_for @project, url: create_project_path, method: :post do |f| %>
    <div class="project-name">
      <div class="project-name-text">프로젝트 제목</div>
      <div class="project-name-form"><%= f.input :name, label: false, autofocus: true, as: :text %></div>
    </div>

    <div class="project-desc">
      <div class="project-desc-text">프로젝트 내용</div>
      <div class="project-desc-form"><%= f.input :desc, label: false %></div>
    </div>

    <div class="action-icon">
      <div class="project-submit">
        확인
      </div>
      <div class="project-cancel">
        취소
      </div>
    </div>
  <% end %>


</div>

app/views/project/new.html.erb
<div class="project">
  <div class="container">
    
    <%= render 'project/form' %>

    <div class="project-upload">
      <%= form_tag create_image_path, method: 'post', id: 'upload-dropzone', remote: true, authenticity_token: true do %>
        
        <!-- <input name="project_name" id="project_name" type="hidden" value=""> -->
        <input name="project_id" id="project_id" type="hidden" value="">

        <div id="upload">
          <%= image_tag asset_path('project/image_upload.png'), class: 'dz-thumbnail dz-image' %>
        </div>
      <% end %>
    </div>
      

    <div id='preview'></div>
      
  </div>

  <form id="hrefPost">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input name="image_id" id="image_id" type="hidden" value="">
    <input name="project_id" id="project_id" type="hidden" value="">
  </form>

</div>

<script type="text/javascript">
  var saveMode = "";
  var projectValidation = false;

  function hrefPost(url,method, image_param, project_name, project_id) {
    $('#hrefPost #image_id').attr('value', image_param);
    $('#hrefPost #project_name').attr('value', project_name);
    $('#hrefPost #project_id').attr('value', project_id);
    $('#hrefPost').attr({action: url, method: method}).submit();
  }

  function createProject(name, desc) {
    param_project_name = name;
    param_project_desc = desc;

    if($('.project-name-form textarea').val() != "") {
      $.ajax({
        type: "POST",
        url: 'projects/validate/'+name,
        success: function(data, status, xhr) {
          if(xhr.status == 200) {

            $.ajax({
              type: "POST",
              url: "<%= create_project_path %>",
              data: { project: { 
                name: param_project_name, 
                desc: param_project_desc }
              },
              success: function(data, status, xhr) {
                $('.project-name-form textarea').text(param_project_name);
                $('.project-desc-form textarea').text(param_project_desc);

                result = $.parseJSON(xhr.responseText);
                
                $('.dropzone #project_name').attr('value', result.name);
                $('.dropzone #project_id').attr('value', result.id);

                if (myDropZone.getQueuedFiles().length > 0) {
                  myDropZone.processQueue();
                } else {
                  hrefPost("/projects/"+result.id, 'get', '', result.name, result.id);
                }
              },
              error: function(data) {

              }
            });

          } else {
            alert("프로젝트가 존재합니다. 이름을 다시 설정해 주세요.");
          }
        }
      });
      
    } else {
      alert("프로젝트 제목을 입력해주세요.");
    }
  }

  $('.action-icon .project-submit').on('click', function(e) {
    if (myDropZone.getQueuedFiles().length === 0) {
      alert('이미지를 업로드 해 주세요.');
      return false;
    }
    createProject($('.project-name-form textarea').val(), $('.project-desc-form textarea').val());
  });

  $('.action-icon .project-cancel').on('click', function(e) {
    window.history.back();
  });

  Dropzone.autoDiscover = false;

  var myDropZone = new Dropzone("#upload-dropzone", {
    // url: "<%= create_image_path %>",
    paramName: 'image[photo]',
    maxFiles: 100,
    addRemoveLinks: false,
    thumbnailWidth: 139,
    thumbnailHeight: 255,
    parallelUploads: 100,
    clickable: '#upload',
    previewContainer: '#preview',
    autoProcessQueue: false,
    previewTemplate: "\<div class=\"dz-preview dz-file-preview\">\n\
    <div class=\"dz-remove\">삭제</div>\n\
    <div class=\"overlay\"><span>이미지 연결</span></div>\n\
    <img class=\"dz-thumbnail\" data-dz-thumbnail>\n\
    <div class=\"dz-filename file-name\"><span data-dz-name></span></div>\n\
      </div>\n\
      ",
    renameFilename: function (file) {
      return file.renameFilename = file.split('.')[0];
    },
    acceptedFiles:'.jpg, .png, .jpeg, .gif',

    init: function(){
      $(this.element).addClass("dropzone");

      this.on('dragenter', function(event) {

      });

      this.on('dragleave', function(event) {

      });

      this.on('success', function(data, status, xhr) {
        result = $.parseJSON(data.xhr.responseText);
        $(data.previewTemplate).attr('id', result.id);
      });
      var clickedTemplate;
      this.on("addedfile", function(file) {

        $(file.previewTemplate).find('.overlay').on('click', function(event) {
          saveMode = "fileClick";
          clickedTemplate = file.previewTemplate;
          createProject($('.project-name-form textarea').val(), $('.project-desc-form textarea').val());
        });

        $(file.previewTemplate).find('.dz-remove').on('click', function(event) {
          clickedValue = $(file.previewElement);
          $(file.previewElement).fadeOut(300, function(e) {
            file.previewElement.parentNode.removeChild(file.previewElement);
          });
        });

      });

      this.on('complete', function(file, json) {
        
      });

      this.on('queuecomplete', function(file) {      
        if (this.getQueuedFiles().length === 0) {
          // name = $('.project-name-form textarea').val();
          name = $('.dropzone #project_name').attr('value');
          id = $('.dropzone #project_id').attr('value');

          if (saveMode == 'fileClick') {
            hrefPost("/projects/"+ id +"/relation", 'post', $(clickedTemplate).attr('id'), $('.dropzone #project_name').attr('value'), id);
          } else {
            hrefPost("/projects/"+id, 'post', '', name, id);
          }
        }
      });
    }
  });
</script>

app/views/project/relation.html.erb
<div class="relation">
<div class="drop-right" style="display:none;">
  <%= image_tag asset_path('project/relation/page_link_drop_right.png'), class: 'message-box'%>
  <div class="title">연결하기:</div>
  <%= image_tag asset_path('project/relation/page_link_drop_right_close.svg'), class: 'close' %>

  <div class="dropdown">
    <div class="drop-title">선택하기</div>
      <div class="arrow-down"> <%= image_tag asset_path('project/relation/arrow-down.svg') %> </div>
      <div class="dropdown-content">
      <% @images.each do |images| %>
        <div class="text-wrap"><div class="text" id="<%= images.id %>"><%= images.photo_file_name %></div></div>
      <% end %>
      </div>
  </div>
  <div class="check">
    확인
  </div>

</div>
<!-- left: 500px; top: 600px; -->
  <div class="container">

    <div class="top-menu">
        <div class="preview-mode" style="float: left;">
          <%= image_tag asset_path('project/preview.png') %>
          <div class="top-menu-dropdown-preview">
            <%= image_tag asset_path('project/preview_hover.svg') %>
          </div>
        </div>
        <div class="link-mode" style="float: left;">
          <%= image_tag asset_path('project/page_link_active.png') %>
          <div class="top-menu-dropdown-link">
            <%= image_tag asset_path('project/page_link_hover.svg') %>
          </div>
        </div>
        <div class="save-mode" style="float: left;">
          <%= image_tag asset_path('project/save.png') %>
          <div class="top-menu-dropdown-save">
            <%= image_tag asset_path('project/save_hover.svg') %>
          </div>
        </div>
        <div style="clear: both;"></div>
    </div>
    
    <%= image_tag asset_path('project/i-phone-6-silver.png'), class: "mobile-wrap" %>
    <div class="mobile-view" style="background-image: url(<%= asset_path @image.photo.url %>)">
      <div id="canvas"></div>
    </div>
    
<!-- https://placeholdit.imgix.net/~text?bg=F6F6F6&txtclr=000000) -->
    <div class="navbar-fixed-bottom menu-image-link">
      <div class="elements">
          <div class="title">이미지 총 <%= @images.size %>장</div>
          <div class="link-menu-close"></div>
        <div class="image-group">
          <div class="image-placeholer">
            <div>
              <%= image_tag asset_path('project/relation/link_upload.svg'), class: "upload-image", style: "margin-top: -170px;" %>
            </div>
            <div class="text" style="visibility:hidden;">hidden</div>
          </div>

          <% @images.each do |images| %>
            <div class="image-placeholer link">
              <%= image_tag "#{images.photo(:thumb)}", class: "link-images", id: "#{images.id}" %>
              <div class="text" id="<%= images.id %>"><%= images.photo_file_name %></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <form id="hrefPost">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input name="image_id" id="image_id" type="hidden" value="">
  </form>
  <div class="preview-name"><%= link_to @project.name, show_project_path(@project.id) %></div>
  <div class="preview-line"></div>
</div>

<script type="text/javascript">
  var select_image_id = null

  function hrefPost(url, param) {
    $('#hrefPost #image_id').attr('value', param);
    $('#hrefPost').attr({action: url, method: 'post'}).submit();
  }

  $(document).on("keydown", function(e) {
    if (e.which == 8) {
      $('.clicked').each(function(index, value) {
        $(this).remove();
        $(".menu-image-link").fadeOut(300);
        $(".drop-title").text("선택하기");
        $(".drop-right").fadeOut(300);

      });
    }
  });

  // $('body').bind("click", function(e) {
  //   $(".menu-image-link").fadeOut(300);
  //   $(".drop-right").fadeOut(300);
  // });

  $('.close').on('click', function(e) {
    $(".menu-image-link").fadeOut(300);
    $(".drop-right").fadeOut(300);
    $('.gen-box-tracker').attr('id', '');
    $(".link-images").each(function(index, value) {
      $(".gen-box-tracker").removeClass('.gen-box-tracker');
    });
    $(".drop-title").text("선택하기");
  });

  $(".top-menu").children().on("click", function(e) {
    var clazz = $(this).attr('class');
    var id = <%= @image.id %>
    if(clazz == "save-mode") {
      gen_boxs = $('*[class^="gen_box_"]');
      saveClickableArea();
      
      hrefPost("/projects/<%= params[:project_id] %>/preview", id);
      // location.href = "<= show_project_path(@project.name) %>";
    } else if(clazz == "preview-mode") {
      hrefPost("/projects/<%= params[:project_id] %>/preview", id);
      // location.href = "/project/<= params[:project_name] %>/preview/"+id;
    }
  });

  $(".link-menu-close").on('click', function(e) {
    $(".menu-image-link").fadeOut(300);
  });

  $(".link").children().on("click", function(e) {
    var children = $(this);
    select_image_id = children.attr('id');
    $('.gen-box-tracker').attr('id', select_image_id);
    $(".gen-box-tracker").removeClass('gen-box-tracker');
    $(".menu-image-link").fadeOut(300);
    $(".drop-right").fadeOut(300);
    $(".drop-title").text("선택하기");
  });

  $(".dropdown").on('click', function(e) {
    if ( $(".dropdown-content").css('display') == 'none') {
      $(".dropdown-content").fadeIn(200);
      $(".menu-image-link").fadeOut(300);
    } else {
      $(".dropdown-content").fadeOut(200);
    }
  });

  $(".dropdown-content").children().on('click', function(e) {
    children = $(this).children();
    select_image_id = children.attr('id');
    $('.gen-box-tracker').attr('id', select_image_id);
    $(".link-images").each(function(index, value) {
      if ($(value).attr('id') == $(".gen-box-tracker").attr('id') && isNullOrUndefined($(".gen-box-tracker").attr('id')) != true) {
        $(value).css('border', 'solid 5px yellow');
        selectText = $(value).parent().find(".text").text();
        $(".text-wrap").find(".text").each(function(dropIndex, dropValue) {
          if($(dropValue).text() == selectText) {
            $(".drop-title").text(selectText);
          }
        });
      } else {
        $(value).css('border', 'solid 5px transparent');
      }
    });
  });

  $(".check").on('click', function(e) {
    $(".gen-box-tracker").removeClass('gen-box-tracker');
    $(".menu-image-link").fadeOut(300);
    $(".drop-right").fadeOut(300);
    $(".drop-title").text("선택하기");
  });

  var mobileView = $('.mobile-view');

  var main_content = $('#canvas');
  var gen_box_count  = 1;

  var main_content_left = parseInt(main_content.offset().left);
  var main_content_top = parseInt(main_content.offset().top);
  var main_content_right = parseInt(main_content_left) + parseInt(mobileView.width());
  var main_content_bottom = parseInt(main_content_top) + parseInt(mobileView.height());
  var name_sequence = 1;

  main_content.on({
    dragstart: function(e) {
      x = e.pageX,
      y = e.pageY;
      $(".hover").css("cursor", "move");
      $(".drop-right").fadeOut(300);
      $(".drop-title").text("선택하기");
      $(".menu-image-link").fadeOut(300);
    },
    resizestart: function(e) {

    },
    dragstop: function(e) {
      $(".hover").css("cursor", "pointer");
    }
  });
  var selected_value;

  main_content.selectable({
    distance: 50,
    
    create: function(e) {
      <% @image.clickables.each do |clickables| %>
        drawGenBox(gen_box_count, "<%= clickables.target_image_id %>", "<%= clickables.width %>", "<%= clickables.height %>", "<%= clickables.left %>", "<%= clickables.top %>");
      <% end %>

    },

    start: function(e) {
      x_begin = e.pageX,
      y_begin = e.pageY;
    },

    stop: function(e) {
      x_end = e.pageX,
      y_end = e.pageY;

      drawGenBox(gen_box_count);
    }});

    function drawGenBox(box_count, box_target_image_id, box_width, box_height, box_left, box_top) {
      var gen_box = null;
      if(isNullOrUndefined(box_width)) {
        if( x_end - x_begin >= 0 ) {
          width  = x_end - x_begin,
          drag_left = false;
        } else {
          width  = x_begin - x_end,
          drag_left = true;
        }
      } else {
        width = parseInt(box_width);
      }

      if(isNullOrUndefined(box_height)) {
        if( y_end - y_begin >= 0) {
          height = y_end - y_begin,
          drag_top = false;
          
        } else {
          height = y_begin - y_end,
          drag_top = true;
        }
      } else {
        height = parseInt(box_height);
      }

      main_content.append('<div class="gen_box_' + box_count + ' '+ "hover"+'"></div>');

      gen_box = $('.gen_box_' + box_count);

      $(".hover").hover(function() {
        $(".hover").css("cursor", "pointer");
      });

      if(isNullOrUndefined(box_target_image_id) != true) {
        $(".link-images").each(function(index, value) {
          if($(value).attr('id') == box_target_image_id) {
            gen_box.attr('id', box_target_image_id);
          }
        });
      }

      gen_box.on("click", function(e) {
        e.stopPropagation();

        clickedGenBox = $(this);

        gen_box_left = parseInt(gen_box.offset().left);
        gen_box_right = parseInt(gen_box_left + gen_box.width());

        $(".drop-right").css({
            'top'   : gen_box.offset().top,
            'left'  : gen_box_right
          });
        
        $(".clicked").each(function(index, value) {
          if( clickedGenBox.attr('class') == $(value).attr('class')) {
            // $(".menu-image-link").fadeOut(300);
            // $(".drop-right").fadeOut(300);
            $(value).removeClass('clicked');
            e.stopPropagation();
          }
        });

        $(".gen-box-tracker").each(function(index, value) {
          if( clickedGenBox.attr('class') == $(value).attr('class') ){
            $(value).removeClass('gen-box-tracker');
            e.stopPropagation();
          }
        });

        gen_box.addClass('gen-box-tracker');
        gen_box.addClass('clicked');
        gen_box.attr('name', name_sequence);
        name_sequence++;

        if( $('.gen-box-tracker').size() != 1) {
          var first = null;
          var second = null;
        $('.gen-box-tracker').each(function(index, value) {
            if(index == 0) {
              first = $(value);
            } else {
              second = $(value);
            }
          });
          if (first.attr('name') > second.attr('name')){
            second.removeClass('gen-box-tracker');
          } else {
            first.removeClass('gen-box-tracker');
          }
        }

        $(".link-images").each(function(index, value) {
          if ($(value).attr('id') == $(".gen-box-tracker").attr('id') && isNullOrUndefined($(".gen-box-tracker").attr('id')) != true) {
            $(value).css('border', 'solid 5px yellow');
            selectText = $(value).parent().find(".text").text();

            $(".text-wrap").find(".text").each(function(dropIndex, dropValue) {
              if($(dropValue).text() == selectText) {
                $(".drop-title").text(selectText);
              }
            });
          } else {
            $(value).css('border', 'solid 5px transparent');
          }
        });


        $(".menu-image-link").fadeIn(300);
        $(".drop-right").fadeIn(300);
      });

      gen_box.css({
        // 'rgba(0, 0, 0, 0.8)'
        'background' : 'rgba(0, 0, 0, 0.4)',
        'width'      : width,
        'height'     : height,
        'position'   : 'absolute'
      })
      .draggable({ containment: "parent" })
      .resizable({ containment: "parent" });

      if(isNullOrUndefined(box_left)) {
        drag_left ? gen_box.offset({ left: x_end }) : gen_box.offset({ left: x_begin });
      } else {
        gen_box.offset({ left: parseInt(box_left)+parseInt(main_content_left) });
      }
      
      if(isNullOrUndefined(box_top)) {
        drag_top ? gen_box.offset({ top: y_end }) : gen_box.offset({ top: y_begin });
      } else {
        gen_box.offset({ top: parseInt(box_top)+parseInt(main_content_top) });
      }
      gen_box_count++;
    }; //drawGenBox

    function check_link() {
      gen_boxs.each(function(index, value) {
        if( isNullOrUndefined($(this).attr('id')) ) {
          alert("이미지를 연결해 주세요");
          e.preventDefault();
        }
      });
    } //check_link

    function destroyClickableArea() {
      $.ajax({
        type: "POST",
        url: "<%= destroy_all_project_image_clickables_path(params[:project_id], @image_id) %>",
        success: function(data) {

        },
        error: function(data) {

        }
      });
    } //destroyClickableArea

    function saveClickableArea() {
      console.info("save start");
      destroyClickableArea();
      gen_boxs.each(function(index, value) {
        $.ajax({
          type: "POST",
          url: "<%= project_image_clickables_path(params[:project_id], @image_id) %>",
          data: { clickable: { 
            target_image_id: $(this).attr('id'),
            top: (parseInt($(this).css('top'))),
            left: (parseInt($(this).css('left'))),
            width: $(this).width(),
            height: $(this).height() } },
          success: function(data) {

          },
          error: function(data) {

          }
        });
      });
    } //saveClickableArea

    function isNullOrUndefined(variable) { return variable === null || variable === undefined; }
</script>